"""New tables added

Revision ID: 32d58d71b78c
Revises: 649fd45c38da
Create Date: 2025-04-22 12:05:34.802642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '32d58d71b78c'
down_revision = '649fd45c38da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
        op.create_table(
        'time_blocks',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, 
                 sa.ForeignKey('scarlet.users.id'), nullable=False),
        sa.Column('task_id', sa.Integer, 
                 sa.ForeignKey('scarlet.tasks.id'), nullable=True),
        sa.Column('start', sa.DateTime(timezone=True), nullable=False),
        sa.Column('end', sa.DateTime(timezone=True), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), 
                  server_default=sa.func.now(), nullable=False),
        schema='scarlet'
        )
    
        # Create index
        op.create_index(
            'idx_timeblock_user_start_end',
            'time_blocks',
            ['user_id', 'start', 'end'],
            schema='scarlet'
        )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop index and table
    op.drop_index(
        'idx_timeblock_user_start_end',
        schema='scarlet',
        table_name='time_blocks'
    )
    op.drop_table('time_blocks', schema='scarlet')
    # ### end Alembic commands ###
