"""Added phone number column

Revision ID: 649fd45c38da
Revises: 75536d6f6be2
Create Date: 2025-04-21 15:08:14.342044

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '649fd45c38da'
down_revision = '75536d6f6be2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema='scarlet') as batch_op:
        batch_op.add_column(sa.Column('phone_number', sa.String(25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'phone_number', schema='scarlet')
    # ### end Alembic commands ###
