"""Notification Modification

Revision ID: 75536d6f6be2
Revises: eb9bfa50473b
Create Date: 2025-04-21 14:46:08.384734

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '75536d6f6be2'
down_revision = 'eb9bfa50473b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.add_column(
        'tasks',
        sa.Column(
            'deadline_notified',
            sa.Boolean(),
            nullable=False,
            server_default=sa.text('false'),
        ),
        schema='scarlet'
    )
    # Once existing rows are populated, you can drop the server_default:
    op.alter_column(
        'tasks',
        'deadline_notified',
        server_default=None,
        schema='scarlet'
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'deadline_notified', schema='scarlet')

    # ### end Alembic commands ###
