"""remove unused table

Revision ID: 871a1e78d627
Revises: 9cf3fc5b612e
Create Date: 2025-04-23 16:26:43.826524

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '871a1e78d627'
down_revision = '9cf3fc5b612e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('time_blocks', 'task_ids', schema='scarlet')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'time_blocks',
        sa.Column('task_ids', sa.ARRAY(sa.Integer()), nullable=True, server_default='{}'),
        schema='scarlet'
    )
    # ### end Alembic commands ###
