"""More Adjustments

Revision ID: 91030f0b6173
Revises: dfe297eee51c
Create Date: 2025-04-25 09:30:45.999826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '91030f0b6173'
down_revision = 'dfe297eee51c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) drop sessions table entirely
    op.drop_table('sessions', schema='scarlet')

    # 2) add soft-delete columns to tasks
    op.add_column('tasks',
        sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
        schema='scarlet'
    )
    op.add_column('tasks',
        sa.Column('permanently_deleted', sa.Boolean(), nullable=False, server_default='false'),
        schema='scarlet'
    )
    # 3) index on deleted_at
    op.create_index('ix_tasks_deleted_at', 'tasks', ['deleted_at'], schema='scarlet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_tasks_deleted_at', table_name='tasks', schema='scarlet')
    op.drop_column('tasks', 'permanently_deleted', schema='scarlet')
    op.drop_column('tasks', 'deleted_at', schema='scarlet')

    # recreate sessions table
    op.create_table(
        'sessions',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('scarlet.users.id'), nullable=False),
        sa.Column('jti', sa.String(36), nullable=False, index=True),
        sa.Column('user_agent', sa.String(256)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema='scarlet')
    # ### end Alembic commands ###
