"""Calender Overhaul

Revision ID: 9cf3fc5b612e
Revises: 32d58d71b78c
Create Date: 2025-04-23 11:53:46.959161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9cf3fc5b612e'
down_revision = '32d58d71b78c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
      # 1) add new column
    op.add_column('time_blocks',
        sa.Column('task_ids', postgresql.ARRAY(sa.Integer()), nullable=True),
        schema='scarlet'
    )
    # 2) migrate existing data: copy task_id → [task_id]
    op.execute("""
        UPDATE scarlet.time_blocks
           SET task_ids = ARRAY[task_id]::integer[]
         WHERE task_id IS NOT NULL
    """)
    # 3) drop old FK and column
    op.drop_constraint('time_blocks_task_id_fkey', 'time_blocks', schema='scarlet', type_='foreignkey')
    op.drop_column('time_blocks', 'task_id', schema='scarlet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('time_blocks',
        sa.Column('task_id', sa.Integer(), nullable=True),
        schema='scarlet'
    )
    op.execute("""
        UPDATE scarlet.time_blocks
           SET task_id = task_ids[1]
         WHERE task_ids IS NOT NULL
    """)
    op.drop_column('time_blocks', 'task_ids', schema='scarlet')
    op.create_foreign_key(
        'time_blocks_task_id_fkey',
        'time_blocks', 'tasks',
        ['task_id'], ['id'],
        source_schema='scarlet', referent_schema='scarlet'
    )
    # ### end Alembic commands ###
