"""Adding Tokenblocklist

Revision ID: b92b4fab7620
Revises: 5a077709134f
Create Date: 2025-04-12 12:42:43.496789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b92b4fab7620'
down_revision = '5a077709134f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokenblocklist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('token_type', sa.String(length=10), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    schema='scarlet'
    )
    with op.batch_alter_table('tokenblocklist', schema='scarlet') as batch_op:
        batch_op.create_index(batch_op.f('ix_scarlet_tokenblocklist_jti'), ['jti'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_behaviors', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_user_behavior_user_id')
        batch_op.drop_index('idx_user_behavior_timestamp')

    op.drop_table('user_behaviors', schema='scarlet')
    with op.batch_alter_table('task_permissions', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_task_permission_user_id')
        batch_op.drop_index('idx_task_permission_task_id')

    op.drop_table('task_permissions', schema='scarlet')
    with op.batch_alter_table('task_behaviors', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_task_behavior_timestamp')
        batch_op.drop_index('idx_task_behavior_task_id')

    op.drop_table('task_behaviors', schema='scarlet')
    with op.batch_alter_table('subtasks', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_subtask_task_id')

    op.drop_table('subtasks', schema='scarlet')
    with op.batch_alter_table('tasks', schema='scarlet') as batch_op:
        batch_op.drop_index('ix_tasks_user_deadline')
        batch_op.drop_index('ix_tasks_priority_status')
        batch_op.drop_index('idx_task_user_id')
        batch_op.drop_index('idx_task_priority')
        batch_op.drop_index('idx_task_deadline')

    op.drop_table('tasks', schema='scarlet')
    op.drop_table('surveys', schema='scarlet')
    with op.batch_alter_table('projects', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_project_created_by')

    op.drop_table('projects', schema='scarlet')
    with op.batch_alter_table('users', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')

    op.drop_table('users', schema='scarlet')
    with op.batch_alter_table('tokenblocklist', schema='scarlet') as batch_op:
        batch_op.drop_index(batch_op.f('ix_scarlet_tokenblocklist_jti'))

    op.drop_table('tokenblocklist', schema='scarlet')
    # ### end Alembic commands ###
