"""Make timestamps timezone aware, use func.now()

Revision ID: bd0618487832
Revises: 19dea1768db8
Create Date: 2025-04-19 12:06:57.161403

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'bd0618487832'
down_revision = '19dea1768db8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    op.execute("""
    ALTER TABLE scarlet.users
      ALTER COLUMN created_at
        TYPE TIMESTAMP WITH TIME ZONE
          USING created_at AT TIME ZONE 'UTC',
      ALTER COLUMN created_at
        SET DEFAULT now();
    """)
    op.execute("""
    ALTER TABLE scarlet.users
      ALTER COLUMN last_login
        TYPE TIMESTAMP WITH TIME ZONE
          USING last_login AT TIME ZONE 'UTC';
    """)
    op.execute("""
    ALTER TABLE scarlet.tasks
      ALTER COLUMN deadline
        TYPE TIMESTAMP WITH TIME ZONE
          USING deadline AT TIME ZONE 'UTC';
    """)
    op.execute("""
    ALTER TABLE scarlet.tasks
      ALTER COLUMN completed_at
        TYPE TIMESTAMP WITH TIME ZONE
          USING completed_at AT TIME ZONE 'UTC';
    """)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_behaviors', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_user_behavior_user_id')
        batch_op.drop_index('idx_user_behavior_timestamp')

    op.drop_table('user_behaviors', schema='scarlet')
    with op.batch_alter_table('task_permissions', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_task_permission_user_id')
        batch_op.drop_index('idx_task_permission_task_id')

    op.drop_table('task_permissions', schema='scarlet')
    with op.batch_alter_table('task_behaviors', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_task_behavior_timestamp')
        batch_op.drop_index('idx_task_behavior_task_id')

    op.drop_table('task_behaviors', schema='scarlet')
    with op.batch_alter_table('subtasks', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_subtask_task_id')

    op.drop_table('subtasks', schema='scarlet')
    with op.batch_alter_table('tasks', schema='scarlet') as batch_op:
        batch_op.drop_index('ix_tasks_user_deadline')
        batch_op.drop_index('ix_tasks_priority_status')
        batch_op.drop_index(batch_op.f('ix_scarlet_tasks_deadline'))
        batch_op.drop_index('idx_task_user_id')
        batch_op.drop_index('idx_task_priority')
        batch_op.drop_index('idx_task_deadline')

    op.drop_table('tasks', schema='scarlet')
    op.drop_table('surveys', schema='scarlet')
    with op.batch_alter_table('projects', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_project_created_by')

    op.drop_table('projects', schema='scarlet')
    with op.batch_alter_table('users', schema='scarlet') as batch_op:
        batch_op.drop_index('idx_user_username')
        batch_op.drop_index('idx_user_email')

    op.drop_table('users', schema='scarlet')
    with op.batch_alter_table('tokenblocklist', schema='scarlet') as batch_op:
        batch_op.drop_index(batch_op.f('ix_scarlet_tokenblocklist_jti'))

    op.drop_table('tokenblocklist', schema='scarlet')
    # ### end Alembic commands ###
