"""Add user security and sessions

Revision ID: dfe297eee51c
Revises: 871a1e78d627
Create Date: 2025-04-23 23:10:12.577030

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'dfe297eee51c'
down_revision = '871a1e78d627'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # user security columns
    op.add_column('users', sa.Column('avatar_url', sa.String(), nullable=True), schema='scarlet')
    op.add_column('users', sa.Column('email_confirmed', sa.Boolean(), nullable=False, server_default=sa.false()), schema='scarlet')
    op.add_column('users', sa.Column('email_confirm_token', sa.String(length=128), nullable=True), schema='scarlet')
    op.add_column('users', sa.Column('phone_confirmed', sa.Boolean(), nullable=False, server_default=sa.false()), schema='scarlet')
    op.add_column('users', sa.Column('phone_confirm_token', sa.String(length=128), nullable=True), schema='scarlet')
    op.add_column('users', sa.Column('totp_secret', sa.String(length=32), nullable=True), schema='scarlet')
    op.add_column('users', sa.Column('is_2fa_enabled', sa.Boolean(), nullable=False, server_default=sa.false()), schema='scarlet')

    # new sessions table
    op.create_table('sessions',
        sa.Column('id', sa.Integer(), primary_key=True),
        sa.Column('user_id', sa.Integer(), sa.ForeignKey('scarlet.users.id'), nullable=False),
        sa.Column('jti', sa.String(length=36), nullable=False, index=True),
        sa.Column('user_agent', sa.String(length=256)),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.func.now()),
        schema='scarlet'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sessions', schema='scarlet')
    for col in ['avatar_url','email_confirmed','email_confirm_token',
                'phone_confirmed','phone_confirm_token','totp_secret','is_2fa_enabled']:
        op.drop_column('users', col, schema='scarlet')
    # ### end Alembic commands ###
