"""New Tag Style

Revision ID: f8e4f0f60b6f
Revises: 91030f0b6173
Create Date: 2025-04-26 21:17:01.536728

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'f8e4f0f60b6f'
down_revision = '91030f0b6173'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 1) drop old tags column
    op.drop_index('idx_task_tags', table_name='tasks', schema='scarlet', if_exists=True)
    op.drop_column('tasks', 'tags', schema='scarlet')

    # 2) create tags table
    op.create_table(
        'tags', 
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('user_id', sa.Integer, sa.ForeignKey('scarlet.users.id', ondelete='CASCADE'), nullable=False),
        sa.Column('name', sa.String(50), nullable=False),
        sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
        sa.CheckConstraint("char_length(name) > 0", name='valid_tag_name'),
        sa.UniqueConstraint('user_id','name', name='uq_tag_user_name'),
        schema='scarlet'
    )

    # 3) create association table
    op.create_table(
        'task_tags',
        sa.Column('task_id', sa.Integer, sa.ForeignKey('scarlet.tasks.id', ondelete='CASCADE'), primary_key=True),
        sa.Column('tag_id', sa.Integer, sa.ForeignKey('scarlet.tags.id', ondelete='CASCADE'), primary_key=True),
        schema='scarlet'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # drop association
    op.drop_table('task_tags', schema='scarlet')
    # drop tags
    op.drop_table('tags', schema='scarlet')
    # add back old tags column
    op.add_column('tasks', sa.Column('tags', sa.ARRAY(sa.String), server_default='{}', nullable=True), schema='scarlet')
    # ### end Alembic commands ###
